services:
  ai.tutorial:
    image: ${DOCKER_REGISTRY-}aitutorial
    build:
      context: .
      dockerfile: AI.Tutorial/Dockerfile
    stdin_open: true  # Keep STDIN open
    tty: true        # Allocate a pseudo-TTY

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
